name: HelloWorld
main: gt.plugin.helloworld.HelloWorld
version: 0.1

commands:
  gg:
    description: Starts a new Last Gnome Game.
  end:
    description: Ends the Last Gnome Game.
  gc:
    description: Runs the GC.
