name: HelloWorld
main: gt.plugin.helloworld.HelloWorld
version: 0.1

commands:
  gg:
    description: Starts a new Last Gnome Game.
  end:
    description: Ends the Last Gnome Game.
  team:
    description: manages the team TODO
  fly:
    description: allows the player to fly
  prompt:
    description: shows the prompt
  instances:
    description: shows open instances
  spectate:
    description: spectates the given instance
  blocktool:
    description: gives a block tool
  
